import config from '../../../config/index'
import { IUser } from './users.interface'
import User from './users.model'
import { autogeneratedId } from './users.utils'

export const createUser = async (user: IUser): Promise<IUser> => {
  //auto incremented genrated user id
  const id = await autogeneratedId()
  user.id = id

  // befor use default password

  if (!user.password) {
    user.password = config.default_user_pass as string
    // as string na dile bolbe je ekhane password string or undefined hote pare .
    // but amra kintu .env filer moddhe string ai diye feleci, tai types assertion hisebe as string
  }

  const createdUser = await User.create(user)
  if (!createUser) {
    throw new Error('Failed to create user')
  }

  return createdUser
}
