import config from '../../../config/index'
import { IUser } from './user.interface'
import User from './user.model'
import { autogeneratedId } from './user.utils'

const createUser = async (user: IUser): Promise<IUser> => {
  //auto incremented genrated user id
  const id = await autogeneratedId()
  user.id = id

  // befor use default password

  if (!user.password) {
    user.password = config.default_user_pass as string
    // as string na dile bolbe je ekhane password string or undefined hote pare .
    // but amra kintu .env filer moddhe string ai diye feleci, tai types assertion hisebe as string
  }

  const createdUser = await User.create(user)
  if (!createUser) {
    throw new Error('Failed to create user')
  }

  return createdUser
}

export const UserService = {
  createUser,
}
