import User from './user.model'

// it use for get last user id
const userLastId = async () => {
  const lastId = await User.findOne({}, { id: 1, _id: 0 })
    .sort({ createdAt: -1 })
    .lean()
  return lastId?.id
}

// if dont found userId from db , then automatcally create or section

export const autogeneratedId = async () => {
  const currentUserId = (await userLastId()) || (0).toString().padStart(5, '0')
  // jodi database a userid na thake , tahole 00000 ta zero create korbe..
  // 00000 diye to id hobe na , tai increment kora lagbe

  const incrementedId = (parseInt(currentUserId) + 1)
    .toString()
    .padStart(5, '0')
  return incrementedId
}
